version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: mylog.log

  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple

loggers:
  my_logger:
    level: INFO
    handlers: [file_handler, console_handler]

root:
  level: DEBUG
  handlers: [file_handler]
